### ISSUE TITLE
Not sure how to use ocp-index properly with Emacs and Merlin

### ISSUE THREAD

**Issue by michipili** [OCamlPro/ocp-index#82]
I am not sure how to use ocp-index properly.

**Merlin** is set-up properly for my project and I can use the `merlin-type-enclosing` function bound to `C-c C-t` to display the type of the expression under point.

When I  `(require ocp-indent)` the function `merlin-type-enclosing` still works but the key combination `C-c C-t` is rebound to `(ocp-index-print-info-at-point)` which now fails with the message `No definition found`.

What is the expected relation between ocp-indent and merlin? What is the proper way to set them up properly?

**Comment by AltGr** [comment]
Although they proceed very differently, there is indeed some overlap in the features of ocp-index and merlin. [user-setup](https://opam.ocaml.org/packages/user-setup/user-setup.0.4/) should handle having both of them correctly. I otherwise would recommend that you load ocp-index's elisp first, then merlin's, so that you get the merlin keybindings you're used to.

`ocp-index-print-info-at-point` outputs the details of the value under point as well as its documentation, when available (this requires .cmt files to be installed) ; but it only works for top-level values as it is gathered on the fly from modules found in your project and libraries. `merlin-type-enclosing`, on the other hand, maintains a state of your buffer and uses the OCaml type-system to show you the type of any expression.

**Comment by michipili** [comment]
Okay thanks! :)
